export const CONTENT_REQUEST = "CONTENT_REQUEST";
export const CONTENT_REQUEST_SUCCESS = "CONTENT_REQUEST_SUCCESS";
export const CONTENT_REQUEST_FAIL = "CONTENT_REQUEST_FAIL";


export const EVENT_REQUEST = "EVENT_REQUEST";
export const EVENT_REQUEST_SUCCESS = "EVENT_REQUEST_SUCCESS";
export const EVENT_REQUEST_FAIL = "EVENT_REQUEST_FAIL";


